@echo off
rem Somatic dev launcher. Every path is derived from this file's location
rem (%~dp0), so the repository can live anywhere and be cloned by anyone.
setlocal
set "HERE=%~dp0"
set "ROOT=%HERE%.."

rem Isolated config: Somatic's own MCP servers, generated by scripts/generate-config.mjs.
set "OPENCODE_CONFIG_DIR=%HERE%3dcoder-config"
set "OPENCODE_DISABLE_EXTERNAL_SKILLS=1"
set "OPENCODE_DISABLE_CLAUDE_CODE_SKILLS=1"
set "CODER3D_CAD_PYTHON=%ROOT%\cad-mcp\.venv\Scripts\python.exe"
rem MCP servers handed to the headless Claude/Codex turn.
set "CODER3D_CLAUDE_MCP_CONFIG=%HERE%3dcoder-config\claude-subagent-mcp.json"

if not exist "%OPENCODE_CONFIG_DIR%\opencode.jsonc" (
  echo Config missing. Run setup.ps1 in the repository root first.
  exit /b 1
)

cd /d "%HERE%"
call bun run dev:desktop
